config/routes.rb
Rails.application.routes.draw do
  resources :bingos do
    collection do
      get :random
      get :generate
      get :self_selected
      post :self_selected
    end
  end
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bingos_controller.rb
class BingosController < ApplicationController
  require "rmagick"

  def index
  end

  def random
  end

  def self_selected
    if params[:card_ids]
      @card_ids = clean_params
    else
      @card_ids = []
    end

    if @card_ids.length == 25 && params[:results]
      @results = results_params

      # @results = @results.to_enum.sort_by(&:last)

      @results = @results.to_enum.to_h.sort_by { |k| k.last.to_i }
    else
      @results = []
    end

    if @results.any? && @results.length <= 25

      images_path = "public/images"
      @file_name = "self_selected.jpg"
      file_path = images_path + "/" + @file_name

      if File.exist? file_path
        File.delete file_path 
      end

      img = Magick::Image.read("lib/sample_images/bingo.png").first

      text = Magick::Draw.new
      text.font = "public/images/simsun.ttc"
      text.pointsize = 35
      text.gravity = Magick::CenterGravity

      x_axis = [ -400, -200, -10, 180, 370 ]
      y_axis = [ -400, -200, -40, 140, 320 ]
      x = 0
      y = 0
      @results.each do |card, value|
        if card.length > 5
          text.pointsize = 20
        else
          text.pointsize = 35
        end

        text.annotate(img, 0,0,x_axis[x] ,y_axis[y], card) { |options|
          options.fill = 'gray83'
        }

        x += 1
        
        if (x==5)
          x = 0
          y += 1
        end 
      end

      self_selected = img.scale(1)
      @path = "/images/" + @file_name + "?timestamp=" + Time.now.to_time.to_i.to_s
      self_selected.write file_path
    end
  end

  def generate
    images_path = "public/images"
    @file_name = "rmagick_generated_thumb.jpg"
    file_path = images_path + "/" + @file_name

    @random_cards = Constants.get_random_card(25)

    if File.exist? file_path
      File.delete file_path 
    end

    img = Magick::Image.read("lib/sample_images/bingo.png").first

    text = Magick::Draw.new
    text.font = "public/images/simsun.ttc"
    text.pointsize = 35
    text.gravity = Magick::CenterGravity

    x_axis = [ -400, -200, -10, 180, 370 ]
    y_axis = [ -400, -200, -40, 140, 320 ]
    x = 0
    y = 0
    @random_cards.each do |card|
      if card.length > 5
        text.pointsize = 20
      else
        text.pointsize = 35
      end

      text.annotate(img, 0,0,x_axis[x] ,y_axis[y], card) { |options|
        options.fill = 'gray83'
      }

      x += 1
      
      if (x==5)
        x = 0
        y += 1
      end 
    end

    thumb = img.scale(1)
    @path = "/images/" + @file_name + "?timestamp=" + Time.now.to_time.to_i.to_s
    thumb.write file_path
  end

  private
    def clean_params
      params.require(:card_ids)
    end

    def results_params
      params.require(:results)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bingo_helper.rb
module BingoHelper
end

app/helpers/bingos_helper.rb
module BingosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/bingos/generate.html.erb
<div class="container">
	<div class="btn-group" role="group" aria-label="Basic example">
		<%= button_to "Random", random_bingos_path, class: "btn btn-primary" %>

		<%= link_to "Download IMAGE", @path, class: "btn btn-secondary ", download: "", target: "_blank" %>
	</div>
	<br>
	<%= link_to image_tag(@path), @path, target: "_blank" %>
</div>

app/views/bingos/random.html.erb
<%#= Constants.get_random_card(25) %>
<div class="container">
	<% i = 1 %>
	<% Constants.get_random_card(25).each do |card| %>
		<% if (i % 5) == 1 %>
			<ul class="list-group list-group-horizontal">
		<% end %>
			<li class="list-group-item"> 
				<%= h card -%>
			</li>
		<% if (i % 5) == 0 %>
			</ul>
		<% end -%>
		<% i += 1 %>
	<% end -%>

	<%= button_to "Random", random_bingos_path, class: "btn btn-primary" %>

	<%= image_tag("bingo.png") %>
</div>

app/views/bingos/self_selected.html.erb
<div class="container">
    <h2>Please select <%= @card_ids.length %> / 25 cards</h2>

    <%= form_with url: self_selected_bingos_path, data: { turbo:false } do |form| %>
        <% i = 1 %>
        
        <% Constants.get_card_list.each do |card| %>
            <% if (i % 5) == 1 %>
                <ul class="list-group list-group-horizontal">
            <% end %>
                    <li class="list-group-item"> 
                        <% if @card_ids.include?(card) %>
                            <%= check_box_tag 'card_ids[]', card, true -%>
                            <%= h card -%>
                        <% else %>
                            <%= check_box_tag 'card_ids[]', card -%>
                            <%= h card -%>
                        <% end -%>
                    </li>
            <% if (i % 5) == 0 %>
                </ul>
            <% end -%>
            <% i += 1 %>
        <% end %>
        <%= form.submit "Selected", class: "btn btn-primary" %>
    <% end %>

    <% if @card_ids.any? && @card_ids.length == 25 %>
        <h2>Custom Weight</h2>

        <%= form_with url: self_selected_bingos_path, class: 'row g-3', data: { turbo:false } do |form| %>

            <% if @results.empty? %>
                <% @card_ids.each do |card| %>
                    <div class="col-md-2">
                        <%= form.label card, class: 'form-label' %>
                        <%= form.text_field 'card_ids[]', value: card, class: 'form-control d-none' %>
                        <%= form.text_field ('results['+card.to_s+']'), class: 'form-control', value: 0 %>
                    </div>
                <% end -%>
            <% else %>
                <% @results.each do |n, v| %>
                    <div class="col-md-2">
                        <%= form.label n, class: 'form-label' %>
                        <%= form.text_field 'card_ids[]', value: n, class: 'form-control d-none' %>
                        <%= form.text_field ('results['+n.to_s+']'), class: 'form-control', value: v %>
                    </div>
                <% end -%>
            <% end -%>
            <div class="col-12">
                <%= form.submit "Changed", class: "btn btn-primary" %>
            </div>
        <% end %>
    <% end -%>

    <% if @results.any? && @results.length == 25 %>
        <%= link_to image_tag(@path), @path, target: "_blank" %>
    <% else %>
        <%= image_tag("bingo.png") %>
    <% end %>
</div>

app/views/home/index.html.erb
<h1>Welcome, this is the home page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Devilcat" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "partitions/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/partitions/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">DevilCat</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Bingo", self_selected_bingos_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Random", generate_bingos_path, class: "nav-link", data: { turbo: false } %>
      </li>
    </ul>
  </div>
</nav>